# Generated by Django 5.0.6 on 2024-09-26 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordersummary',
            name='total',
            field=models.FloatField(null=True),
        ),
    ]
