# Generated by Django 5.0.6 on 2024-09-29 06:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0003_reviews'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reviews',
            old_name='user_onject',
            new_name='user_object',
        ),
    ]
