# Generated by Django 5.0.6 on 2024-10-10 06:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0007_product_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(choices=[('honey', 'honey'), ('ghee', 'ghee'), ('coconut_oil', 'coconut_oil')], default='honey', max_length=100),
        ),
    ]
