# Generated by Django 5.0.6 on 2024-10-12 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0009_product_category_remove_product_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='pro_cat_object',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='mystore.product_category'),
        ),
    ]
