# Generated by Django 5.0.6 on 2024-10-15 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mystore', '0010_alter_product_pro_cat_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordersummary',
            name='payment_methode',
            field=models.CharField(choices=[('online_payment', 'online_payment'), ('cash_on_delivery', 'cash_on_delivery')], default='online_payment', max_length=200),
        ),
    ]
